Add support for moving folders to system trash
voidcosmos/npkill pull request #113
Opened 2021-10-16 18:01 UTC by Fleker

Adds a `--trash` flag to the CLI to move a `node_modules` to system trash rather than deleting directly.

To use the `trash` module, the project needs to be rewritten to use ESModules
There is one test still outstanding that isn't running as I work out some compat issues, but wanted to create this now to solicit some feedback.

See #60

2022-03-03 09:06 UTC, mrbaguvix requested changes
Nice one adding the `--trash` option but if adding one single feature could make rewriting most of the original project structure, i don't think it is ideal for a merge. You can look for a typescript port for `trash` lib or an alternative package.

2022-03-03 09:06 UTC, mrbaguvix commented on src/constants/index.ts
> +export * from './recursive-rmdir-node-support.constants.js';
Just curious why suffix file names with `.js` extension?

2022-03-03 09:06 UTC, mrbaguvix commented on src/services/index.ts
> +export * from './windows-files.service.js';
huh?

2022-10-09 13:29 UTC, zaldih commented
Hi!
It's been a while since I had to decide what to do whith this precious PR. The problem is that initially I didn't really understand why it was necessary to modify so many things just for the feature, so one of the tasks I thought to do was to "upate" the other lib to make it compatible with projects like this. Actually the one who was wrong was me since the future points to ESM although eve today it is still experimental.
That is why I finally decided to update the project with ESM (already in develop branch).

Now that there should be no more ESM problems, **could you reopen the PR with only the changes related to the feature?** I will merge it as soon as possible. Thank!

2022-10-09 13:29 UTC, closed without merging